version: '3.9'

services:
  api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    depends_on:
      - init-db
    networks:
      - backend

  init-db:
    build: .
    container_name: db-init
    command: python startup.py
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development


  spa:
    build: ../kosmoJODD_SPA
    container_name: kosmoJODD-SPA
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge